name: 'Learn Github Actions'
on: [push]
jobs:
  check-nodejs-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '15'
    - run: node -v
    - run: npm -v
